// lib/countryCurrency.ts
//
// Maps a country name (as used in the Basics country dropdown) to its primary
// currency ISO code. Used to auto-fill the salary currency when the user picks
// where they live now. Falls back to USD when a country isn't mapped.

const COUNTRY_CURRENCY: Record<string, string> = {
  // --- North America ---
  "United States": "USD",
  Canada: "CAD",
  Mexico: "MXN",

  // --- Europe (euro zone) ---
  Ireland: "EUR",
  France: "EUR",
  Germany: "EUR",
  Netherlands: "EUR",
  Belgium: "EUR",
  Luxembourg: "EUR",
  Austria: "EUR",
  Finland: "EUR",
  Portugal: "EUR",
  Spain: "EUR",
  Italy: "EUR",
  Greece: "EUR",
  Cyprus: "EUR",
  Malta: "EUR",
  Croatia: "EUR",
  Estonia: "EUR",
  Latvia: "EUR",
  Lithuania: "EUR",
  Slovakia: "EUR",
  Slovenia: "EUR",
  Kosovo: "EUR",

  // --- Europe (non-euro) ---
  "United Kingdom": "GBP",
  Switzerland: "CHF",
  Denmark: "DKK",
  Sweden: "SEK",
  Norway: "NOK",
  Iceland: "ISK",
  "Czech Republic": "CZK",
  Poland: "PLN",
  Hungary: "HUF",
  Romania: "RON",
  Bulgaria: "BGN",
  Georgia: "GEL",
  Albania: "ALL",
  Bosnia: "BAM",
  Serbia: "RSD",
  Moldova: "MDL",
  Ukraine: "UAH",
  Belarus: "BYN",
  Russia: "RUB",
  Turkey: "TRY",

  // --- Middle East ---
  Israel: "ILS",
  "United Arab Emirates": "AED",
  "Saudi Arabia": "SAR",
  Qatar: "QAR",
  Kuwait: "KWD",
  Oman: "OMR",
  Jordan: "JOD",
  Lebanon: "LBP",
  Iran: "IRR",
  Iraq: "IQD",
  Syria: "SYP",
  Yemen: "YER",
  Palestine: "ILS",

  // --- Asia ---
  Singapore: "SGD",
  Japan: "JPY",
  "South Korea": "KRW",
  "North Korea": "KPW",
  "Hong Kong": "HKD",
  Taiwan: "TWD",
  Thailand: "THB",
  Malaysia: "MYR",
  Vietnam: "VND",
  China: "CNY",
  India: "INR",
  Pakistan: "PKR",
  Bangladesh: "BDT",
  "Sri Lanka": "LKR",
  Nepal: "NPR",
  Indonesia: "IDR",
  Philippines: "PHP",
  Cambodia: "KHR",
  Laos: "LAK",
  Myanmar: "MMK",
  Mongolia: "MNT",
  Kazakhstan: "KZT",
  Kyrgyzstan: "KGS",
  Tajikistan: "TJS",
  Turkmenistan: "TMT",
  Uzbekistan: "UZS",
  Afghanistan: "AFN",
  Armenia: "AMD",
  Azerbaijan: "AZN",

  // --- Oceania ---
  Australia: "AUD",
  "New Zealand": "NZD",

  // --- Latin America ---
  "Costa Rica": "CRC",
  Panama: "USD",
  Uruguay: "UYU",
  Argentina: "ARS",
  Brazil: "BRL",
  Chile: "CLP",
  Colombia: "COP",
  Peru: "PEN",
  Bolivia: "BOB",
  Ecuador: "USD",
  Paraguay: "PYG",
  Venezuela: "VES",
  Guatemala: "GTQ",
  Honduras: "HNL",
  Nicaragua: "NIO",
  "El Salvador": "USD",
  Cuba: "CUP",
  Jamaica: "JMD",

  // --- Africa ---
  "South Africa": "ZAR",
  Egypt: "EGP",
  Morocco: "MAD",
  Tunisia: "TND",
  Algeria: "DZD",
  Libya: "LYD",
  Nigeria: "NGN",
  Kenya: "KES",
  Ghana: "GHS",
  Ethiopia: "ETB",
  Tanzania: "TZS",
  Uganda: "UGX",
  Rwanda: "RWF",
  Senegal: "XOF",
  Cameroon: "XAF",
  Angola: "AOA",
  Congo: "CDF",
  Zambia: "ZMW",
  Zimbabwe: "ZWL",
  Somalia: "SOS",
  Sudan: "SDG",
};

/** Returns the primary currency ISO code for a country, or "USD" if unmapped. */
export function currencyForCountry(country: string | undefined): string {
  if (!country) return "USD";
  return COUNTRY_CURRENCY[country] ?? "USD";
}
