// lib/countriesDb.ts

export type CultureCluster =
  | "northern_europe"
  | "western_europe"
  | "southern_europe"
  | "mediterranean"
  | "north_america"
  | "latin_america"
  | "asia"
  | "oceania"
  | "middle_east"
  | "post_soviet"
  | "other";

export type CountryRecord = {
  code: string;
  name: string;

  /** 0–10, higher = better for someone who wants *lower effective personal taxes* */
  taxScore: number;

  /** 0–10, higher = better = cheaper relative to income potential (for a remote earner) */
  costOfLivingScore: number;

  /** 0–10, higher = better income / career upside for remote / international workers */
  incomeGrowthScore: number;

  /** 0–10, remote friendliness: banking, infrastructure, nomad friendliness, etc. */
  remoteFriendlyScore: number;

  /** 0–10, personal safety + political stability blended */
  safetyScore: number;

  /** 0–10, lifestyle / vibe: food, culture, nature, social life, overall quality of life */
  lifestyleScore: number;

  /** Climate “fit” components (0–10) for that climate type */
  coldClimateScore?: number;
  mildClimateScore?: number;
  warmClimateScore?: number;

  /** 0–10, how easy life is with English only (10 = almost everywhere) */
  englishScore?: number;

  /** 0–10, size & integration of expat / international community */
  expatSceneScore?: number;

  /** 0–10, social life / nightlife / events */
  socialSceneScore?: number;

  /** 0–10, LGBT legal protections + social acceptance */
  lgbtScore?: number;

  /** 0–10 overall healthcare quality + accessibility for residents */
  healthcareScore?: number;

  /**
   * 0–10, where it sits on “public vs private” axis:
   * 0–3 = heavily private, 4–6 = mixed, 7–10 = strong public system.
   */
  healthcarePublicTilt?: number;

  /** 0–10, how “developed” it feels day-to-day (infrastructure + services + cleanliness) */
  developmentScore?: number;

  /** 0–10, public transport quality in major cities + ability to live without a car */
  publicTransportScore?: number;

  /** 0–10, digital services (e-gov, online banking, payments, ID) */
  digitalServicesScore?: number;

  /** 0–10, cleanliness / maintenance of streets & public space */
  infrastructureCleanScore?: number;

  /** 0–10, availability of cafes, delivery, coworking, everyday services */
  everydayServicesScore?: number;

  /** Cultural group tags used to match the “culture_*” answers */
  cultureClusters: CultureCluster[];

  /** Main languages most useful in big cities (names aligned with your LANGUAGE_OPTIONS where possible) */
  mainLanguages: string[];

  /** Typical % of income kept after income tax + social contributions for a mid-ish remote earner using reasonable optimisation */
  netIncomePercentTypical: number;

  /** Short human note shown in the UI */
  shortNote: string;
};

/**
 * COUNTRIES
 *
 * All values are approximate 0–10 scores, tuned for:
 *  - Remote workers / e-com / freelancers
 *  - People comparing relocation destinations
 *  - Realistic balance (not extreme) but opinionated where it matters (LGBT, safety, development).
 */
export const COUNTRIES: CountryRecord[] = [
  /* --------------------------- North America --------------------------- */
  {
    code: "US",
    name: "United States",
    taxScore: 6, // big variation by state
    costOfLivingScore: 5,
    incomeGrowthScore: 9,
    remoteFriendlyScore: 8.5,
    safetyScore: 6.5,
    lifestyleScore: 8,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 8,
    englishScore: 10,
    expatSceneScore: 8.5,
    socialSceneScore: 9,
    lgbtScore: 8,
    healthcareScore: 7.5, // high quality, expensive
    healthcarePublicTilt: 2.5,
    developmentScore: 8.5,
    publicTransportScore: 6, // strong only in some cities
    digitalServicesScore: 8,
    infrastructureCleanScore: 7,
    everydayServicesScore: 9,
    cultureClusters: ["north_america"],
    mainLanguages: ["English", "Spanish"],
    netIncomePercentTypical: 70,
    shortNote:
      "Huge income upside with very big-city options, but private healthcare and uneven safety.",
  },
  {
    code: "CA",
    name: "Canada",
    taxScore: 4.5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 8,
    safetyScore: 9,
    lifestyleScore: 7.5,
    coldClimateScore: 9,
    mildClimateScore: 6,
    warmClimateScore: 3,
    englishScore: 9.5,
    expatSceneScore: 8,
    socialSceneScore: 7,
    lgbtScore: 9,
    healthcareScore: 8,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 7,
    digitalServicesScore: 8,
    infrastructureCleanScore: 8.5,
    everydayServicesScore: 8,
    cultureClusters: ["north_america"],
    mainLanguages: ["English", "French"],
    netIncomePercentTypical: 65,
    shortNote:
      "Very safe, progressive and cold, with public healthcare and decent income prospects.",
  },
  {
    code: "MX",
    name: "Mexico",
    taxScore: 7,
    costOfLivingScore: 8.5,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7,
    safetyScore: 4.5, // varies a lot
    lifestyleScore: 8,
    coldClimateScore: 4.5,
    mildClimateScore: 7,
    warmClimateScore: 8.5,
    englishScore: 5.5,
    expatSceneScore: 8,
    socialSceneScore: 8,
    lgbtScore: 7,
    healthcareScore: 6.5,
    healthcarePublicTilt: 5.5,
    developmentScore: 7,
    publicTransportScore: 6,
    digitalServicesScore: 6.5,
    infrastructureCleanScore: 5.5,
    everydayServicesScore: 8,
    cultureClusters: ["latin_america"],
    mainLanguages: ["Spanish", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Warm, affordable and social with strong expat hubs; safety is very city-dependent.",
  },

  /* ------------------------- Western / Northern EU ------------------------- */
  {
    code: "GB",
    name: "United Kingdom",
    taxScore: 5,
    costOfLivingScore: 3.5,
    incomeGrowthScore: 8,
    remoteFriendlyScore: 8.5,
    safetyScore: 7.5,
    lifestyleScore: 8,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 3,
    englishScore: 10,
    expatSceneScore: 9,
    socialSceneScore: 9,
    lgbtScore: 8.5,
    healthcareScore: 8,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 8.5,
    digitalServicesScore: 8.5,
    infrastructureCleanScore: 8,
    everydayServicesScore: 9,
    cultureClusters: ["western_europe", "northern_europe"],
    mainLanguages: ["English"],
    netIncomePercentTypical: 64,
    shortNote:
      "English-speaking big-city hub with strong LGBT rights and NHS, but high costs.",
  },
  {
    code: "IE",
    name: "Ireland",
    taxScore: 5.5,
    costOfLivingScore: 4,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 8,
    safetyScore: 8.5,
    lifestyleScore: 7.5,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 2.5,
    englishScore: 10,
    expatSceneScore: 8,
    socialSceneScore: 7.5,
    lgbtScore: 9,
    healthcareScore: 7,
    healthcarePublicTilt: 7,
    developmentScore: 8.5,
    publicTransportScore: 7,
    digitalServicesScore: 8,
    infrastructureCleanScore: 8,
    everydayServicesScore: 8,
    cultureClusters: ["western_europe", "northern_europe"],
    mainLanguages: ["English"],
    netIncomePercentTypical: 64,
    shortNote:
      "English-speaking EU base with strong protections and a big tech footprint, but expensive.",
  },
  {
    code: "FR",
    name: "France",
    taxScore: 4.5,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 7.5,
    lifestyleScore: 9,
    coldClimateScore: 6,
    mildClimateScore: 8,
    warmClimateScore: 7,
    englishScore: 6,
    expatSceneScore: 7.5,
    socialSceneScore: 8,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 9.5,
    developmentScore: 9,
    publicTransportScore: 8.5,
    digitalServicesScore: 8,
    infrastructureCleanScore: 8,
    everydayServicesScore: 8.5,
    cultureClusters: ["western_europe", "mediterranean"],
    mainLanguages: ["French", "English"],
    netIncomePercentTypical: 63,
    shortNote:
      "Strong public services and amazing lifestyle, with high taxes and bureaucracy.",
  },
  {
    code: "DE",
    name: "Germany",
    taxScore: 4.5,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 7.5,
    safetyScore: 8.5,
    lifestyleScore: 7.5,
    coldClimateScore: 7.5,
    mildClimateScore: 7,
    warmClimateScore: 4.5,
    englishScore: 7,
    expatSceneScore: 7.5,
    socialSceneScore: 7,
    lgbtScore: 8.5,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 9,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 8.5,
    everydayServicesScore: 8,
    cultureClusters: ["western_europe", "northern_europe"],
    mainLanguages: ["German", "English"],
    netIncomePercentTypical: 62,
    shortNote:
      "Very strong public systems and transport; mid-high taxes but excellent stability.",
  },
  {
    code: "NL",
    name: "Netherlands",
    taxScore: 4.5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 8,
    remoteFriendlyScore: 9,
    safetyScore: 9,
    lifestyleScore: 8.5,
    coldClimateScore: 7,
    mildClimateScore: 7,
    warmClimateScore: 4,
    englishScore: 9.5,
    expatSceneScore: 9,
    socialSceneScore: 7.5,
    lgbtScore: 9.5,
    healthcareScore: 8.5,
    healthcarePublicTilt: 7,
    developmentScore: 9.5,
    publicTransportScore: 9,
    digitalServicesScore: 9,
    infrastructureCleanScore: 8.5,
    everydayServicesScore: 9,
    cultureClusters: ["western_europe", "northern_europe"],
    mainLanguages: ["Dutch", "English"],
    netIncomePercentTypical: 63,
    shortNote:
      "Ultra English-friendly, very developed, very LGBT-friendly but high tax & cost of living.",
  },
  {
    code: "BE",
    name: "Belgium",
    taxScore: 3.5,
    costOfLivingScore: 5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 8,
    lifestyleScore: 7.5,
    coldClimateScore: 7,
    mildClimateScore: 7,
    warmClimateScore: 4,
    englishScore: 8,
    expatSceneScore: 7,
    socialSceneScore: 7,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 8,
    digitalServicesScore: 8,
    infrastructureCleanScore: 8,
    everydayServicesScore: 8,
    cultureClusters: ["western_europe", "northern_europe"],
    mainLanguages: ["French", "Dutch", "English"],
    netIncomePercentTypical: 60,
    shortNote:
      "High taxes but excellent public services and strong protections; very central in Europe.",
  },
  {
    code: "LU",
    name: "Luxembourg",
    taxScore: 5.5,
    costOfLivingScore: 3.5,
    incomeGrowthScore: 8.5,
    remoteFriendlyScore: 8,
    safetyScore: 9,
    lifestyleScore: 7.5,
    coldClimateScore: 7,
    mildClimateScore: 7,
    warmClimateScore: 4,
    englishScore: 8.5,
    expatSceneScore: 8,
    socialSceneScore: 6.5,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 8,
    developmentScore: 9.5,
    publicTransportScore: 8.5,
    digitalServicesScore: 8.5,
    infrastructureCleanScore: 9,
    everydayServicesScore: 8,
    cultureClusters: ["western_europe"],
    mainLanguages: ["French", "German", "Luxembourgish", "English"],
    netIncomePercentTypical: 68,
    shortNote:
      "Tiny, extremely rich, safe and very international, but expensive and quiet.",
  },
  {
    code: "CH",
    name: "Switzerland",
    taxScore: 7,
    costOfLivingScore: 2.5,
    incomeGrowthScore: 9,
    remoteFriendlyScore: 8,
    safetyScore: 9.5,
    lifestyleScore: 8.5,
    coldClimateScore: 8.5,
    mildClimateScore: 7,
    warmClimateScore: 3.5,
    englishScore: 7.5,
    expatSceneScore: 8,
    socialSceneScore: 7,
    lgbtScore: 8,
    healthcareScore: 9,
    healthcarePublicTilt: 5,
    developmentScore: 9.5,
    publicTransportScore: 9.5,
    digitalServicesScore: 8,
    infrastructureCleanScore: 9.5,
    everydayServicesScore: 8.5,
    cultureClusters: ["western_europe"],
    mainLanguages: ["German", "French", "Italian", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Extremely safe and high-income, with very high living costs and private-leaning healthcare.",
  },
  {
    code: "AT",
    name: "Austria",
    taxScore: 5,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 9,
    lifestyleScore: 8,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 3.5,
    englishScore: 7,
    expatSceneScore: 7,
    socialSceneScore: 7,
    lgbtScore: 8.5,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 9,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 9,
    everydayServicesScore: 8,
    cultureClusters: ["western_europe"],
    mainLanguages: ["German", "English"],
    netIncomePercentTypical: 63,
    shortNote:
      "Calm, safe and very high quality of life, especially in Vienna; taxes mid–high.",
  },
  {
    code: "DK",
    name: "Denmark",
    taxScore: 3.5,
    costOfLivingScore: 4,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 8.5,
    safetyScore: 9.5,
    lifestyleScore: 8.5,
    coldClimateScore: 9,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 9.5,
    expatSceneScore: 7.5,
    socialSceneScore: 7.5,
    lgbtScore: 9.5,
    healthcareScore: 9,
    healthcarePublicTilt: 9.5,
    developmentScore: 9.5,
    publicTransportScore: 9,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9,
    everydayServicesScore: 8.5,
    cultureClusters: ["northern_europe"],
    mainLanguages: ["Danish", "English"],
    netIncomePercentTypical: 60,
    shortNote:
      "Very progressive, extremely safe and developed, with very high taxes and cool climate.",
  },
  {
    code: "SE",
    name: "Sweden",
    taxScore: 4,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 8.5,
    safetyScore: 9,
    lifestyleScore: 8,
    coldClimateScore: 9,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 9.5,
    expatSceneScore: 7.5,
    socialSceneScore: 7,
    lgbtScore: 9.5,
    healthcareScore: 8.5,
    healthcarePublicTilt: 9,
    developmentScore: 9.5,
    publicTransportScore: 9,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9,
    everydayServicesScore: 8.5,
    cultureClusters: ["northern_europe"],
    mainLanguages: ["Swedish", "English"],
    netIncomePercentTypical: 62,
    shortNote:
      "Cool climate, very high equality and safety, with strong public services and high taxes.",
  },
  {
    code: "NO",
    name: "Norway",
    taxScore: 4.5,
    costOfLivingScore: 3.5,
    incomeGrowthScore: 8,
    remoteFriendlyScore: 8,
    safetyScore: 9.5,
    lifestyleScore: 8,
    coldClimateScore: 9.5,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 9.5,
    expatSceneScore: 7,
    socialSceneScore: 6.5,
    lgbtScore: 9.5,
    healthcareScore: 9,
    healthcarePublicTilt: 9.5,
    developmentScore: 9.5,
    publicTransportScore: 8.5,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9.5,
    everydayServicesScore: 8,
    cultureClusters: ["northern_europe"],
    mainLanguages: ["Norwegian", "English"],
    netIncomePercentTypical: 64,
    shortNote:
      "Very rich, safe and egalitarian, with cold climate and extremely high prices.",
  },
  {
    code: "FI",
    name: "Finland",
    taxScore: 4.5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 8,
    safetyScore: 9.5,
    lifestyleScore: 8,
    coldClimateScore: 9.5,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 9.5,
    expatSceneScore: 6.5,
    socialSceneScore: 6.5,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 9.5,
    developmentScore: 9.5,
    publicTransportScore: 8.5,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9.5,
    everydayServicesScore: 8,
    cultureClusters: ["northern_europe"],
    mainLanguages: ["Finnish", "English", "Swedish"],
    netIncomePercentTypical: 63,
    shortNote:
      "Ultra safe, very digital, cold and dark winters but strong social model and services.",
  },
  {
    code: "IS",
    name: "Iceland",
    taxScore: 4.5,
    costOfLivingScore: 2.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 9.5,
    lifestyleScore: 8,
    coldClimateScore: 9.5,
    mildClimateScore: 6,
    warmClimateScore: 1,
    englishScore: 10,
    expatSceneScore: 6,
    socialSceneScore: 6.5,
    lgbtScore: 9.5,
    healthcareScore: 8.5,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 6.5,
    digitalServicesScore: 8.5,
    infrastructureCleanScore: 9,
    everydayServicesScore: 7.5,
    cultureClusters: ["northern_europe"],
    mainLanguages: ["Icelandic", "English"],
    netIncomePercentTypical: 60,
    shortNote:
      "Tiny, very progressive and safe, extremely expensive with harsh climate and small scene.",
  },

  /* ------------------------- Southern / Med Europe ------------------------- */
  {
    code: "PT",
    name: "Portugal",
    taxScore: 5.5,
    costOfLivingScore: 7,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7,
    safetyScore: 8.5,
    lifestyleScore: 8.5,
    coldClimateScore: 4,
    mildClimateScore: 8,
    warmClimateScore: 7,
    englishScore: 7,
    expatSceneScore: 8,
    socialSceneScore: 7.5,
    lgbtScore: 9,
    healthcareScore: 8,
    healthcarePublicTilt: 8.5,
    developmentScore: 8,
    publicTransportScore: 7,
    digitalServicesScore: 7,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 8,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["Portuguese", "English"],
    netIncomePercentTypical: 68,
    shortNote:
      "Chill Western Europe with strong LGBT rights, good safety and relatively lower costs.",
  },
  {
    code: "ES",
    name: "Spain",
    taxScore: 5,
    costOfLivingScore: 7,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 7,
    safetyScore: 8,
    lifestyleScore: 9,
    coldClimateScore: 4,
    mildClimateScore: 8,
    warmClimateScore: 8,
    englishScore: 6,
    expatSceneScore: 8,
    socialSceneScore: 9,
    lgbtScore: 9.5,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 8.5,
    publicTransportScore: 8,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 8.5,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["Spanish", "English", "Catalan"],
    netIncomePercentTypical: 66,
    shortNote:
      "Big-city and coastal lifestyle, excellent public healthcare and very LGBT-friendly.",
  },
  {
    code: "IT",
    name: "Italy",
    taxScore: 4.5,
    costOfLivingScore: 6,
    incomeGrowthScore: 5.5,
    remoteFriendlyScore: 6.5,
    safetyScore: 7.5,
    lifestyleScore: 9,
    coldClimateScore: 5.5,
    mildClimateScore: 8,
    warmClimateScore: 7.5,
    englishScore: 5.5,
    expatSceneScore: 7,
    socialSceneScore: 8,
    lgbtScore: 7.5,
    healthcareScore: 8.5,
    healthcarePublicTilt: 9,
    developmentScore: 8,
    publicTransportScore: 7.5,
    digitalServicesScore: 6.5,
    infrastructureCleanScore: 7,
    everydayServicesScore: 8.5,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["Italian", "English"],
    netIncomePercentTypical: 64,
    shortNote:
      "Iconic lifestyle, food and culture, with mid–high taxes and bureaucracy.",
  },
  {
    code: "GR",
    name: "Greece",
    taxScore: 4.5,
    costOfLivingScore: 6.5,
    incomeGrowthScore: 5.5,
    remoteFriendlyScore: 6.5,
    safetyScore: 8,
    lifestyleScore: 8.5,
    coldClimateScore: 4,
    mildClimateScore: 8,
    warmClimateScore: 8,
    englishScore: 7,
    expatSceneScore: 7,
    socialSceneScore: 8,
    lgbtScore: 7,
    healthcareScore: 7,
    healthcarePublicTilt: 7.5,
    developmentScore: 7.5,
    publicTransportScore: 6.5,
    digitalServicesScore: 6.5,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 7.5,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["Greek", "English"],
    netIncomePercentTypical: 64,
    shortNote:
      "Mediterranean lifestyle with improving digital services and mid-high taxes.",
  },
  {
    code: "CY",
    name: "Cyprus",
    taxScore: 7.5,
    costOfLivingScore: 6,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7,
    safetyScore: 8,
    lifestyleScore: 7,
    coldClimateScore: 2,
    mildClimateScore: 7,
    warmClimateScore: 8,
    englishScore: 8,
    expatSceneScore: 7,
    socialSceneScore: 6.5,
    lgbtScore: 6.5,
    healthcareScore: 7,
    healthcarePublicTilt: 6.5,
    developmentScore: 7,
    publicTransportScore: 4.5,
    digitalServicesScore: 6,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 6.5,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["Greek", "English"],
    netIncomePercentTypical: 75,
    shortNote:
      "Mediterranean island with friendly taxes for foreign earners and a growing expat scene.",
  },
  {
    code: "MT",
    name: "Malta",
    taxScore: 6.5,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7.5,
    safetyScore: 8,
    lifestyleScore: 7.5,
    coldClimateScore: 2,
    mildClimateScore: 7.5,
    warmClimateScore: 8,
    englishScore: 9,
    expatSceneScore: 7,
    socialSceneScore: 7,
    lgbtScore: 9.5,
    healthcareScore: 8,
    healthcarePublicTilt: 8,
    developmentScore: 7.5,
    publicTransportScore: 6.5,
    digitalServicesScore: 7,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 7,
    cultureClusters: ["mediterranean", "southern_europe"],
    mainLanguages: ["English", "Maltese"],
    netIncomePercentTypical: 70,
    shortNote:
      "Tiny English-speaking EU island with strong LGBT protections and a lot of sun.",
  },

  /* -------------------------- Central / Eastern EU -------------------------- */
  {
    code: "CZ",
    name: "Czech Republic",
    taxScore: 7,
    costOfLivingScore: 7,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 8.5,
    lifestyleScore: 8,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 4,
    englishScore: 7.5,
    expatSceneScore: 8,
    socialSceneScore: 8,
    lgbtScore: 7,
    healthcareScore: 8,
    healthcarePublicTilt: 8,
    developmentScore: 8.5,
    publicTransportScore: 8.5,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 8,
    cultureClusters: ["post_soviet", "western_europe"],
    mainLanguages: ["Czech", "English"],
    netIncomePercentTypical: 76,
    shortNote:
      "Prague is a major expat hub: affordable by EU standards, safe, and central.",
  },
  {
    code: "PL",
    name: "Poland",
    taxScore: 7,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 7,
    safetyScore: 8,
    lifestyleScore: 7,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 3.5,
    englishScore: 7,
    expatSceneScore: 7,
    socialSceneScore: 7.5,
    lgbtScore: 4.5,
    healthcareScore: 7,
    healthcarePublicTilt: 7.5,
    developmentScore: 8,
    publicTransportScore: 8,
    digitalServicesScore: 8,
    infrastructureCleanScore: 7,
    everydayServicesScore: 7.5,
    cultureClusters: ["post_soviet"],
    mainLanguages: ["Polish", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Affordable and fast-growing EU country with good infrastructure but weaker LGBT climate.",
  },
  {
    code: "HU",
    name: "Hungary",
    taxScore: 7.5,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 6.5,
    safetyScore: 7.5,
    lifestyleScore: 7.5,
    coldClimateScore: 7.5,
    mildClimateScore: 7,
    warmClimateScore: 4,
    englishScore: 6.5,
    expatSceneScore: 7,
    socialSceneScore: 8,
    lgbtScore: 3.5,
    healthcareScore: 6.5,
    healthcarePublicTilt: 7,
    developmentScore: 7.5,
    publicTransportScore: 8,
    digitalServicesScore: 7,
    infrastructureCleanScore: 7,
    everydayServicesScore: 7.5,
    cultureClusters: ["post_soviet"],
    mainLanguages: ["Hungarian", "English"],
    netIncomePercentTypical: 80,
    shortNote:
      "Budapest is lively and cheap with low taxes, but LGBT rights and politics are problematic.",
  },
  {
    code: "RO",
    name: "Romania",
    taxScore: 8,
    costOfLivingScore: 8,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7,
    safetyScore: 7,
    lifestyleScore: 7,
    coldClimateScore: 7,
    mildClimateScore: 6.5,
    warmClimateScore: 5,
    englishScore: 6.5,
    expatSceneScore: 6,
    socialSceneScore: 7,
    lgbtScore: 4.5,
    healthcareScore: 5.5,
    healthcarePublicTilt: 6,
    developmentScore: 6.5,
    publicTransportScore: 6.5,
    digitalServicesScore: 7,
    infrastructureCleanScore: 5.5,
    everydayServicesScore: 6.5,
    cultureClusters: ["post_soviet", "southern_europe"],
    mainLanguages: ["Romanian", "English"],
    netIncomePercentTypical: 80,
    shortNote:
      "Very tax-friendly and cheap, but weaker LGBT protections and healthcare.",
  },
  {
    code: "BG",
    name: "Bulgaria",
    taxScore: 8.5,
    costOfLivingScore: 8.5,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 6.5,
    safetyScore: 7,
    lifestyleScore: 6.5,
    coldClimateScore: 7,
    mildClimateScore: 6.5,
    warmClimateScore: 5,
    englishScore: 6,
    expatSceneScore: 5.5,
    socialSceneScore: 6.5,
    lgbtScore: 4,
    healthcareScore: 5,
    healthcarePublicTilt: 5.5,
    developmentScore: 6,
    publicTransportScore: 6,
    digitalServicesScore: 6,
    infrastructureCleanScore: 5.5,
    everydayServicesScore: 6,
    cultureClusters: ["post_soviet"],
    mainLanguages: ["Bulgarian", "English"],
    netIncomePercentTypical: 82,
    shortNote:
      "Flat low tax and cheap, but less developed and relatively weak LGBT protections.",
  },
  {
    code: "HR",
    name: "Croatia",
    taxScore: 6,
    costOfLivingScore: 7,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 7,
    safetyScore: 8.5,
    lifestyleScore: 8,
    coldClimateScore: 7,
    mildClimateScore: 8,
    warmClimateScore: 6,
    englishScore: 7.5,
    expatSceneScore: 7,
    socialSceneScore: 7.5,
    lgbtScore: 6.5,
    healthcareScore: 7.5,
    healthcarePublicTilt: 8,
    developmentScore: 7.5,
    publicTransportScore: 7,
    digitalServicesScore: 7,
    infrastructureCleanScore: 7,
    everydayServicesScore: 7.5,
    cultureClusters: ["mediterranean", "post_soviet"],
    mainLanguages: ["Croatian", "English"],
    netIncomePercentTypical: 72,
    shortNote:
      "Coastal EU country with good safety and lifestyle; mid-level taxes and services.",
  },
  {
    code: "EE",
    name: "Estonia",
    taxScore: 8,
    costOfLivingScore: 7,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 9,
    safetyScore: 8.5,
    lifestyleScore: 7,
    coldClimateScore: 9,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 9,
    expatSceneScore: 6.5,
    socialSceneScore: 6.5,
    lgbtScore: 7.5,
    healthcareScore: 7.5,
    healthcarePublicTilt: 8,
    developmentScore: 9,
    publicTransportScore: 7.5,
    digitalServicesScore: 10,
    infrastructureCleanScore: 8,
    everydayServicesScore: 7.5,
    cultureClusters: ["northern_europe", "post_soviet"],
    mainLanguages: ["Estonian", "English", "Russian"],
    netIncomePercentTypical: 80,
    shortNote:
      "Digital-first EU state with friendly corporate tax, cold winters and good governance.",
  },
  {
    code: "LV",
    name: "Latvia",
    taxScore: 7,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 7,
    safetyScore: 8,
    lifestyleScore: 6.5,
    coldClimateScore: 9,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 8,
    expatSceneScore: 6,
    socialSceneScore: 6.5,
    lgbtScore: 6,
    healthcareScore: 6.5,
    healthcarePublicTilt: 7,
    developmentScore: 7.5,
    publicTransportScore: 7,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 7,
    cultureClusters: ["northern_europe", "post_soviet"],
    mainLanguages: ["Latvian", "English", "Russian"],
    netIncomePercentTypical: 78,
    shortNote:
      "Small Baltic state: relatively affordable, safe and increasingly digital.",
  },
  {
    code: "LT",
    name: "Lithuania",
    taxScore: 7.5,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 8,
    lifestyleScore: 7,
    coldClimateScore: 9,
    mildClimateScore: 7,
    warmClimateScore: 2,
    englishScore: 8,
    expatSceneScore: 6.5,
    socialSceneScore: 6.5,
    lgbtScore: 5.5,
    healthcareScore: 6.5,
    healthcarePublicTilt: 7,
    developmentScore: 7.5,
    publicTransportScore: 7,
    digitalServicesScore: 8,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 7,
    cultureClusters: ["northern_europe", "post_soviet"],
    mainLanguages: ["Lithuanian", "English", "Russian"],
    netIncomePercentTypical: 80,
    shortNote:
      "Growing Baltic tech hub, affordable with decent services and colder climate.",
  },

  /* --------------------------- Georgia / Israel --------------------------- */
  {
    code: "GE",
    name: "Georgia",
    taxScore: 8.5,
    costOfLivingScore: 9,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 7.5,
    safetyScore: 7.5,
    lifestyleScore: 7,
    coldClimateScore: 7,
    mildClimateScore: 7,
    warmClimateScore: 6,
    englishScore: 6,
    expatSceneScore: 7,
    socialSceneScore: 7,
    lgbtScore: 3.5,
    healthcareScore: 5.5,
    healthcarePublicTilt: 4.5,
    developmentScore: 6.5,
    publicTransportScore: 6,
    digitalServicesScore: 6.5,
    infrastructureCleanScore: 5.5,
    everydayServicesScore: 7,
    cultureClusters: ["post_soviet", "asia", "other"],
    mainLanguages: ["Georgian", "Russian", "English"],
    netIncomePercentTypical: 82,
    shortNote:
      "Very tax-light and cheap, big nomad scene in Tbilisi, but limited LGBT protections.",
  },
  {
    code: "IL",
    name: "Israel",
    taxScore: 3.5,
    costOfLivingScore: 2.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 7.5,
    safetyScore: 5.5,
    lifestyleScore: 7.5,
    coldClimateScore: 3,
    mildClimateScore: 6,
    warmClimateScore: 8,
    englishScore: 7.5,
    expatSceneScore: 6.5,
    socialSceneScore: 8,
    lgbtScore: 7.5,
    healthcareScore: 8,
    healthcarePublicTilt: 8.5,
    developmentScore: 8,
    publicTransportScore: 6.5,
    digitalServicesScore: 8,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 8,
    cultureClusters: ["middle_east", "mediterranean"],
    mainLanguages: ["Hebrew", "English", "Arabic"],
    netIncomePercentTypical: 55,
    shortNote:
      "High-tax, high-cost tech hub with strong public healthcare and intense lifestyle.",
  },

  /* ------------------------------ Asia hubs ------------------------------ */
  {
    code: "SG",
    name: "Singapore",
    taxScore: 8.5,
    costOfLivingScore: 3.5,
    incomeGrowthScore: 9,
    remoteFriendlyScore: 9,
    safetyScore: 9.5,
    lifestyleScore: 8.5,
    coldClimateScore: 1,
    mildClimateScore: 3,
    warmClimateScore: 9.5,
    englishScore: 9.5,
    expatSceneScore: 9,
    socialSceneScore: 8,
    lgbtScore: 7, // legal change improving, socially mixed
    healthcareScore: 9,
    healthcarePublicTilt: 7,
    developmentScore: 10,
    publicTransportScore: 9.5,
    digitalServicesScore: 9.5,
    infrastructureCleanScore: 10,
    everydayServicesScore: 9.5,
    cultureClusters: ["asia"],
    mainLanguages: ["English", "Chinese (Mandarin)", "Malay", "Tamil"],
    netIncomePercentTypical: 85,
    shortNote:
      "Hyper-developed, safe and English-speaking city-state with low taxes and very high costs.",
  },
  {
    code: "JP",
    name: "Japan",
    taxScore: 5.5,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7,
    safetyScore: 9.5,
    lifestyleScore: 9,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 6,
    englishScore: 4.5,
    expatSceneScore: 7,
    socialSceneScore: 8,
    lgbtScore: 6, // protections expanding slowly
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 9.5,
    publicTransportScore: 10,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 9.5,
    everydayServicesScore: 9,
    cultureClusters: ["asia"],
    mainLanguages: ["Japanese"],
    netIncomePercentTypical: 68,
    shortNote:
      "Extremely safe and organized with amazing transport; language and bureaucracy can be tough.",
  },
  {
    code: "KR",
    name: "South Korea",
    taxScore: 6,
    costOfLivingScore: 5.5,
    incomeGrowthScore: 7.5,
    remoteFriendlyScore: 8,
    safetyScore: 9,
    lifestyleScore: 8.5,
    coldClimateScore: 8,
    mildClimateScore: 7,
    warmClimateScore: 5,
    englishScore: 6,
    expatSceneScore: 7.5,
    socialSceneScore: 9,
    lgbtScore: 4.5, // socially conservative, limited legal
    healthcareScore: 9,
    healthcarePublicTilt: 8,
    developmentScore: 9.5,
    publicTransportScore: 9.5,
    digitalServicesScore: 9.5,
    infrastructureCleanScore: 9,
    everydayServicesScore: 9,
    cultureClusters: ["asia"],
    mainLanguages: ["Korean", "English"],
    netIncomePercentTypical: 70,
    shortNote:
      "Very high-tech and fast-paced, with great infrastructure; LGBT and work culture are demanding.",
  },
  {
    code: "HK",
    name: "Hong Kong",
    taxScore: 9,
    costOfLivingScore: 2.5,
    incomeGrowthScore: 9,
    remoteFriendlyScore: 8,
    safetyScore: 7.5,
    lifestyleScore: 8,
    coldClimateScore: 3,
    mildClimateScore: 6,
    warmClimateScore: 8,
    englishScore: 8.5,
    expatSceneScore: 9,
    socialSceneScore: 9,
    lgbtScore: 7,
    healthcareScore: 8.5,
    healthcarePublicTilt: 6.5,
    developmentScore: 9.5,
    publicTransportScore: 9.5,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9,
    everydayServicesScore: 9.5,
    cultureClusters: ["asia"],
    mainLanguages: ["Chinese (Cantonese)", "English", "Chinese (Mandarin)"],
    netIncomePercentTypical: 86,
    shortNote:
      "Low-tax, ultra-dense city with huge income potential and very high housing costs.",
  },
  {
    code: "TW",
    name: "Taiwan",
    taxScore: 7,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 9,
    lifestyleScore: 8,
    coldClimateScore: 5,
    mildClimateScore: 7,
    warmClimateScore: 8,
    englishScore: 6,
    expatSceneScore: 7,
    socialSceneScore: 7.5,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 8.5,
    publicTransportScore: 8.5,
    digitalServicesScore: 8.5,
    infrastructureCleanScore: 8.5,
    everydayServicesScore: 8.5,
    cultureClusters: ["asia"],
    mainLanguages: ["Chinese (Mandarin)", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Democratic, safe Asian hub with excellent healthcare and very strong LGBT rights.",
  },
  {
    code: "TH",
    name: "Thailand",
    taxScore: 7,
    costOfLivingScore: 9,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7,
    safetyScore: 7,
    lifestyleScore: 8.5,
    coldClimateScore: 1,
    mildClimateScore: 3,
    warmClimateScore: 9.5,
    englishScore: 6,
    expatSceneScore: 8.5,
    socialSceneScore: 9,
    lgbtScore: 7,
    healthcareScore: 7.5,
    healthcarePublicTilt: 6,
    developmentScore: 7,
    publicTransportScore: 6.5,
    digitalServicesScore: 7,
    infrastructureCleanScore: 6,
    everydayServicesScore: 8.5,
    cultureClusters: ["asia"],
    mainLanguages: ["Thai", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Warm, affordable and social, with improving LGBT climate and good private healthcare.",
  },
  {
    code: "MY",
    name: "Malaysia",
    taxScore: 8,
    costOfLivingScore: 8.5,
    incomeGrowthScore: 6.5,
    remoteFriendlyScore: 7.5,
    safetyScore: 7.5,
    lifestyleScore: 7.5,
    coldClimateScore: 1,
    mildClimateScore: 3,
    warmClimateScore: 9,
    englishScore: 7.5,
    expatSceneScore: 7,
    socialSceneScore: 7.5,
    lgbtScore: 2.5, // legally hostile
    healthcareScore: 8,
    healthcarePublicTilt: 6.5,
    developmentScore: 7.5,
    publicTransportScore: 7,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 7.5,
    everydayServicesScore: 8,
    cultureClusters: ["asia"],
    mainLanguages: ["Malay", "English", "Chinese (Mandarin)"],
    netIncomePercentTypical: 82,
    shortNote:
      "Very affordable, modern in big cities, English widely used, but LGBT situation is restrictive.",
  },
  {
    code: "VN",
    name: "Vietnam",
    taxScore: 7.5,
    costOfLivingScore: 9,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7,
    safetyScore: 7.5,
    lifestyleScore: 8,
    coldClimateScore: 4,
    mildClimateScore: 6,
    warmClimateScore: 9,
    englishScore: 6,
    expatSceneScore: 8,
    socialSceneScore: 8.5,
    lgbtScore: 6,
    healthcareScore: 6.5,
    healthcarePublicTilt: 5.5,
    developmentScore: 7,
    publicTransportScore: 5.5,
    digitalServicesScore: 7,
    infrastructureCleanScore: 6,
    everydayServicesScore: 8,
    cultureClusters: ["asia"],
    mainLanguages: ["Vietnamese", "English"],
    netIncomePercentTypical: 80,
    shortNote:
      "Popular nomad destination: very affordable and lively, still developing in infrastructure.",
  },

  /* ------------------------------ Oceania ------------------------------ */
  {
    code: "AU",
    name: "Australia",
    taxScore: 5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 8,
    remoteFriendlyScore: 8,
    safetyScore: 9,
    lifestyleScore: 9,
    coldClimateScore: 6,
    mildClimateScore: 8,
    warmClimateScore: 8,
    englishScore: 10,
    expatSceneScore: 9,
    socialSceneScore: 8.5,
    lgbtScore: 9,
    healthcareScore: 9,
    healthcarePublicTilt: 9,
    developmentScore: 9.5,
    publicTransportScore: 7.5,
    digitalServicesScore: 8.5,
    infrastructureCleanScore: 9,
    everydayServicesScore: 9,
    cultureClusters: ["oceania", "north_america"],
    mainLanguages: ["English"],
    netIncomePercentTypical: 66,
    shortNote:
      "English-speaking, high-income, very safe with strong healthcare and a relaxed lifestyle.",
  },
  {
    code: "NZ",
    name: "New Zealand",
    taxScore: 5.5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 9.5,
    lifestyleScore: 8.5,
    coldClimateScore: 7,
    mildClimateScore: 8,
    warmClimateScore: 5,
    englishScore: 10,
    expatSceneScore: 7.5,
    socialSceneScore: 7,
    lgbtScore: 9.5,
    healthcareScore: 8.5,
    healthcarePublicTilt: 9,
    developmentScore: 9,
    publicTransportScore: 6.5,
    digitalServicesScore: 8,
    infrastructureCleanScore: 9,
    everydayServicesScore: 8,
    cultureClusters: ["oceania"],
    mainLanguages: ["English"],
    netIncomePercentTypical: 64,
    shortNote:
      "Very safe, nature-rich and progressive English-speaking country at the end of the world.",
  },

  /* ----------------------------- Middle East ----------------------------- */
  {
    code: "AE",
    name: "United Arab Emirates",
    taxScore: 9.5,
    costOfLivingScore: 4.5,
    incomeGrowthScore: 8,
    remoteFriendlyScore: 8,
    safetyScore: 9,
    lifestyleScore: 8,
    coldClimateScore: 1,
    mildClimateScore: 3,
    warmClimateScore: 9.5,
    englishScore: 8.5,
    expatSceneScore: 9,
    socialSceneScore: 8.5,
    lgbtScore: 1, // very restrictive
    healthcareScore: 8,
    healthcarePublicTilt: 4.5,
    developmentScore: 9.5,
    publicTransportScore: 7,
    digitalServicesScore: 9,
    infrastructureCleanScore: 9,
    everydayServicesScore: 9,
    cultureClusters: ["middle_east"],
    mainLanguages: ["Arabic", "English"],
    netIncomePercentTypical: 90,
    shortNote:
      "Tax-free, hyper-modern and safe, but legally very restrictive for LGBT and personal freedoms.",
  },

  /* --------------------------- Latin America --------------------------- */
  {
    code: "CR",
    name: "Costa Rica",
    taxScore: 7,
    costOfLivingScore: 7,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 7,
    safetyScore: 7,
    lifestyleScore: 8.5,
    coldClimateScore: 3,
    mildClimateScore: 6,
    warmClimateScore: 9,
    englishScore: 6.5,
    expatSceneScore: 8,
    socialSceneScore: 7,
    lgbtScore: 7,
    healthcareScore: 7.5,
    healthcarePublicTilt: 7.5,
    developmentScore: 7,
    publicTransportScore: 5.5,
    digitalServicesScore: 6.5,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 7,
    cultureClusters: ["latin_america"],
    mainLanguages: ["Spanish", "English"],
    netIncomePercentTypical: 78,
    shortNote:
      "Stable, eco-focused country with a big expat community and relatively good LGBT situation.",
  },
  {
    code: "PA",
    name: "Panama",
    taxScore: 8,
    costOfLivingScore: 7.5,
    incomeGrowthScore: 7,
    remoteFriendlyScore: 7.5,
    safetyScore: 6.5,
    lifestyleScore: 7.5,
    coldClimateScore: 1,
    mildClimateScore: 4,
    warmClimateScore: 9,
    englishScore: 6.5,
    expatSceneScore: 7.5,
    socialSceneScore: 7.5,
    lgbtScore: 5.5,
    healthcareScore: 7.5,
    healthcarePublicTilt: 6.5,
    developmentScore: 7.5,
    publicTransportScore: 6,
    digitalServicesScore: 7,
    infrastructureCleanScore: 6.5,
    everydayServicesScore: 7.5,
    cultureClusters: ["latin_america"],
    mainLanguages: ["Spanish", "English"],
    netIncomePercentTypical: 80,
    shortNote:
      "Territorial tax system and tropical climate, with growing expat hubs and mid-level safety.",
  },
  {
    code: "UY",
    name: "Uruguay",
    taxScore: 6,
    costOfLivingScore: 6,
    incomeGrowthScore: 6,
    remoteFriendlyScore: 6.5,
    safetyScore: 8,
    lifestyleScore: 8,
    coldClimateScore: 5,
    mildClimateScore: 7,
    warmClimateScore: 7,
    englishScore: 5.5,
    expatSceneScore: 6.5,
    socialSceneScore: 7,
    lgbtScore: 9,
    healthcareScore: 8,
    healthcarePublicTilt: 8,
    developmentScore: 7.5,
    publicTransportScore: 6.5,
    digitalServicesScore: 7.5,
    infrastructureCleanScore: 7,
    everydayServicesScore: 7.5,
    cultureClusters: ["latin_america"],
    mainLanguages: ["Spanish"],
    netIncomePercentTypical: 70,
    shortNote:
      "Calm, democratic and progressive corner of South America with strong LGBT rights.",
  },
];
